# Generated by Django 4.0.5 on 2022-07-02 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionproduct_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 14, 22, 20, 880256)),
        ),
    ]
