# Generated by Django 4.0.5 on 2022-07-02 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionproduct_active_alter_auctionproduct_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='creater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 16, 55, 15, 995048)),
        ),
    ]
