# Generated by Django 4.0.5 on 2022-07-02 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionproduct_creater_alter_auctionproduct_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 16, 56, 0, 308802)),
        ),
    ]
