# Generated by Django 4.0.5 on 2022-07-02 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionproduct_creater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='creater',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 17, 4, 12, 434681)),
        ),
    ]
