# Generated by Django 4.0.5 on 2022-07-03 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_bids_alter_auctionproduct_time_delete_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 17, 15, 28, 82412)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 17, 15, 28, 82412)),
        ),
    ]
