# Generated by Django 4.0.5 on 2022-07-04 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auctionproduct_time_alter_bids_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winnes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 18, 20, 6, 803044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 18, 20, 6, 803044)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 18, 20, 6, 803044)),
        ),
    ]
