# Generated by Django 4.0.5 on 2022-07-05 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auctionproduct_time_alter_bids_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 16, 18, 23, 547412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 16, 18, 23, 547412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 16, 18, 23, 547412, tzinfo=utc)),
        ),
    ]
